### ISSUE TITLE
Heap exhaustion in SBCL when loading lisp-binary from Quicklisp

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [j3pic/lisp-binary#3]
When attempting to load lisp-binary from Quicklisp in SBCL on x64 Ubuntu Linux, I'm getting heap exhaustion during garbage collection:

CL-USER> (ql:quickload :lisp-binary)
To load "lisp-binary":
  Load 1 ASDF system:
    lisp-binary
; Loading "lisp-binary"
..................................................
[package lisp-binary].............................
.........................
CL-USER> (format t "~:D" (sb-ext:dynamic-space-size))
1,073,741,824
NIL

Heap exhausted during garbage collection: 48 bytes available, 80 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 10737418    0   0  0,0000
   1: 23421 23424     0     0 11056  4358     0     0    16 503874848 1211104 299799946    0   1  1,3608
   2: 32766 32763     0     0 11001  4925    56    68   153 521300000 4626400  2000000 1404   0  0,2076
   3:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0,0000
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0,0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0,0000
   6:     0     0     0     0  1094   210     0     0     0 42729472     0  2000000  954   0  0,0000
   Total bytes allocated    = 1067904320
   Dynamic-space-size bytes = 1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 26187(tid 140737231681280):
Heap exhausted, game over.

-----

Is this a known issue? Is there a workaround for it?

Thanks for your assistance,
David

**Comment by rtmpdavid** [comment]
Can confirm, same thing happens to me.

It seems that it happens when SBCL tries to load binary.lisp, particularly when it is compiling expand-defbinary-type-field.
Commenting it out, and loading the function after package is loaded or moving the function to another file seems to help.

The function in question is pretty damn big, but CCL loads the package fine as it is, so it's probably a bug in SBCL.
Edit:
Yep, that seems to be the [case](https://bugs.launchpad.net/sbcl/+bug/1557590)

**Comment by EclecticSoftwareEngineer** [comment]
Yep, looks like you're probably right about that bug. Thanks for looking into it. Next chance I get, I will try that workaround and see how it goes. I've been looking forward to trying it out!

Thanks,
David

**Comment by phoe** [comment]
Any news on this?

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I only recently got access to 64-bit hardware. This bug does not affect 32-bit versions of SBCL. 

I will look into the problem soon.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
It looks like a bug in certain versions of SBCL. I've found that the bug does not affect SBCL 1.1.6 on the Mac. Perhaps this version also works better on 64-bit Linux installations.

The SBCL bug is still unassigned.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I'm going to close this issue because it's a bug in SBCL and not in LISP-BINARY.
