### ISSUE TITLE
This library should not upgrade ASDF

### ISSUE THREAD

**Issue by phoe** [j3pic/lisp-binary#30]
According to the principle of least astonishment, I would never expect a library for reading binary data to have a side effect of upgrading my ASDF version.

What was the use case for that at all? If you had an implementation that had an ancient ASDF, why not patch it on the implementation level, so it bundles a new enough version of ASDF?

I think that 7afc4236 should be reverted.

**Comment by j3pic** [comment]
That was a fix to https://github.com/j3pic/lisp-binary/issues/7, which I attempted to get resolved in https://github.com/quicklisp/quicklisp-client/issues/166, but alas, Quicklisp still comes with ASDF 2.26, so the only way to close https://github.com/j3pic/lisp-binary/issues/7 was to bundle ASDF into Lisp-Binary.

**Comment by j3pic** [comment]
In fact, after rereading the Quicklisp bug, it's evident that bundling ASDF was Xach's idea.

**Comment by j3pic** [comment]
One could argue about whether CLOSER-MOP and Moptilities are actually required by Lisp-Binary. If I got rid of them, I wouldn't have a dependency on ASDF 3.

**Comment by j3pic** [comment]
I addressed this with #32 . If you evaluate `(pushnew :lisp-binary/never-use-own-asdf *features*)` before loading Lisp-Binary, it will not load the bundled version of ASDF, even if it's required for successful loading.
