### ISSUE TITLE
Does not build in latest SBCL - type problem

### ISSUE THREAD

**Issue by quicklisp** [j3pic/lisp-binary#35]
This line seems to declare `*standard-input*` to be of type `keyword`, which signals a full warning in the latest sbcl.

https://github.com/j3pic/lisp-binary/blob/ef019b01e20039f4ed2ac6b2895a6f40f8d8026a/binary-1.lisp#L620

Full log here: http://report.quicklisp.org/2019-12-20/failure-report/lisp-binary.html#lisp-binary

**Comment by j3pic** [comment]
Fixed by https://github.com/j3pic/lisp-binary/pull/36.
