### ISSUE TITLE
Documentation: missing information

### ISSUE THREAD

**Issue by phoe** [j3pic/lisp-binary#4]
In an example,
```lisp
              (defbinary stays-non-byte-aligned ()
                 (x 0 :type 3))
```

What does the `0` after the `x` mean? I could not find this in the documentation for `DEFBINARY`.

**Comment by j3pic** [comment]
@phoe The 0 is the default value of `x` if you create a `stays-non-byte-aligned` object without specifying its value, just like `defstruct`.

**Comment by j3pic** [comment]
@heegaiximephoomeeghahyaiseekh This is not to suggest that this shouldn't be explicitly stated in the documentation. I was able to figure it out, but it doesn't actually say that in the docstring.
