### ISSUE TITLE
read-integer constantly returns zero on closed socket stream

### ISSUE THREAD

**Issue by jaeschliman** [j3pic/lisp-binary#42]
Hello, nice library!
This could just be a matter of documenting?
I see that read-integer uses read-sequence via read-bytes but doesn't check that bytes-read is non-zero. however since bytes-read is returned as the second value, the user can check this condition for themselves.
But it is unexpected, (expect an error in my opinion) and it would be nice if it was noted in the docstring.

**Comment by j3pic** [comment]
That's not the intended behavior, and it causes problems for `read-binary`. I'll add an error if `read-bytes` fails to read all the expected bytes.

**Comment by j3pic** [comment]
I'm providing a `CONTINUE` restart in case you want READ-BYTES to ignore the error like it used to.

**Comment by j3pic** [comment]
In case it's important, the error will be of type `CL:END-OF-FILE`.
