### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [j3pic/lisp-binary#43]
Building with SBCL 2.1.0.29-a1ce59262 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 02ce88f285ef4c8e8b3c2be3385217490fab9628

*lisp-binary-test* fails to build because of a failure in  _lisp-binary_.

*lisp-binary* fails to build with the following error:

```
; caught WARNING:
;   Derived type of SEQUENCE is (OR VECTOR SB-KERNEL:EXTENDED-SEQUENCE), conflicting with its asserted type LIST.
;   See also:
;     The SBCL Manual, Node "Handling of Types"
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "lisp-binary" "utils">

```

[Full log here](http://report.quicklisp.org/2021-01-17/failure-report/lisp-binary.html)

**Comment by phoe** [comment]
https://github.com/j3pic/lisp-binary/blob/02ce88f285ef4c8e8b3c2be3385217490fab9628/utils.lisp#L293-L297

In L297, `mapcar` is called on a non-list sequence, which is an error. This is fixable via replacing the call with `(map 'list function sequence)`.

**Comment by j3pic** [comment]
Thanks for the detailed bug report. It turns out that `mapseq` is can be implemented as just a `map` call.
