### ISSUE TITLE
Heap exhaustion when reading structs

### ISSUE THREAD

**Issue by JoeAnonymous** [j3pic/lisp-binary#55]
Oftentimes when I attempt to read from to a binary struct, I get a heap-exhausted-error. 

What should one do to prevent this from happening, would closing some other applications suffice?

EDIT: I should state that I have written the file to immediately read an object on loading, so I don't think this is garbage collection.

**Comment by j3pic** [comment]
It depends on what's causing the error. I'd be able to give a more exact answer if you provided an example that exhausts the heap (both code and data).

The most likely cause of the error is that your Lisp environment's heap size is too small for the data you're trying to read. You can try increasing the heap size (use the `--dynamic-space-size` argument if you're using SBCL), or defining your struct in such a way that it reads only as much data as fits on the heap.

**Comment by JoeAnonymous** [comment]
Hello, i just realized what the problem was, it had to do with counted-string. i thought it could be used to read the first four bytes of a .WAD header.

This issue was on me, sorry.
