### ISSUE TITLE
Using macros to build custom types

### ISSUE THREAD

**Issue by JoeAnonymous** [j3pic/lisp-binary#58]
Let's say i have a custom reader and writer function that I want to convert into a macro to add to my structs.

Here's an example.

> (defmacro test-custom (size)
>    `(custom 
>         :reader (lambda (stream) (read-bytes ,size stream))
>         :writer (lambda (object stream) (write-bytes object stream ,size))))
> 
> (defbinary test
>     (a 0 :type (eval (test-custom 1))))

I'm not entirely sure if this would even work, because despite it passing compilation I don't think defbinary actually registered that this is a custom read and write function. So is there any conceivable way this could work?

Thank you.

**Comment by j3pic** [comment]
Make `test-custom` a function instead of a macro:
```common-lisp
(defun test-custom (size)
  `(custom :reader (lambda (stream) (read-bytes ,size stream))
	   :writer (lambda (obj stream) (write-bytes object stream ,size))))

(defbinary test ()
  (a 0 :type (eval (test-custom 1))))

```

**Comment by j3pic** [comment]
Be advised: The code that gets generated to read this type is:

```common-lisp
(READ-BINARY-TYPE (TEST-CUSTOM 1) #:STREAM-SYMBOL-789 :BYTE-ORDER
                  :LITTLE-ENDIAN :ALIGN NIL :ELEMENT-ALIGN NIL)
```

...which generates the reader code at runtime and then uses `eval` to run it. Something similar is generated for writing.

**Comment by JoeAnonymous** [comment]
i see, thank you very much
