### ISSUE TITLE
Slots of `:include`d structures not read

### ISSUE THREAD

**Issue by phmarek** [j3pic/lisp-binary#64]
```lisp
(lisp-binary:defbinary foo ()
  (slot-1 0 :type (unsigned-byte 8)))

(lisp-binary:defbinary bar (:include foo)
  (slot-2 0 :type (unsigned-byte 8)))
```

When reading a structure `BAR`, `SLOT-1` is never read in - and so the whole data is read from offsets and wrong.
Eg. `SLOT-2` is read from the position where `SLOT-1` resides in the binary.

I guess that all `:include`d structures' slots must be (recursively?) used in the constructor.

**Comment by phmarek** [comment]
See 6c753125ee6f4ee35ea2a051a331601aef5c4b2a for one solution draft.

**Comment by j3pic** [comment]
Your solution draft passed the test I wrote for it.
