### ISSUE TITLE
Dependencies are fucked in the latest Quicklisp distro in SBCL 1.1.6.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [j3pic/lisp-binary#7]
They removed LISP-BINARY from Quicklisp, but also, Moptilities and CLOSER-MOP seem to be broken on SBCL 1.1.6, which is the latest version available for MacOS.

I don't know if the problem is the SBCL version or if the libraries are just broken.

There are no known workarounds.

My CCL installation is still working, but that may be because I'm using an older version of those libraries.

**Comment by stassats** [comment]
1.1.6 is not the latest version for macOS...

**Comment by photz** [comment]
I also couldn't get lisp-binary to compile with the Quicklisp versions of the libraries you mentioned, but when I take the latest versions directly from Github and put them into Quicklisp's local-projects directory, then it compiles alright... Although for some reason sbcl consumes up to 4 gb of memory during compilation, so unless I increase its dynamic-space-size parameter accordingly, it crashes.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
The version of ASDF being shipped with Quicklisp and/or SBCL is too old for Moptilities and CLOSER-MOP. I've found it necessary to manually upgrade it.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I'm closing this because it's a problem with Quicklisp, not with this library. I filed a bug report against `quicklisp-client`:

https://github.com/quicklisp/quicklisp-client/issues/166
