### ISSUE TITLE
Annoying inline-expansion warning in Lispworks

### ISSUE THREAD

**Issue by calsys456** [j3pic/lisp-binary#70]
Using `read-binary-type` and `write-binary-type` will produce annoying `Warning: inline-expansion cannot be found` in Lispworks while compiling, and I found that just putting the inline declaim before the declaration of the definition of functions will solve this problem - For example, moving line 856 of `binary-1.lisp` to line 839. However, besides of those annoying warnings, the functionality of the code have no problem, though I haven't profile the potential performance improvement.

Do you think it's matter and should make a change? I'm not very clear about whether there's potentially bad point for such a change.

And, Lisp-binary performs very well in Lispworks for me, even under heavy multiprocessing. Thank you very much :D!

**Comment by j3pic** [comment]
I can't afford LispWorks, so I can't debug anything there. This library doesn't compile in the trial edition because of memory limitations.

Feel free to make a PR with the change you're describing. I'll merge it if it passes tests on SBCL.

**Comment by calsys456** [comment]
Thanks! Sorry for my late response, and I've create a pull request about that. #73 

Hope I can make something helpful.
