### ISSUE TITLE
SBCL runs out of heap space during compilation

### ISSUE THREAD

**Issue by photz** [j3pic/lisp-binary#8]
Hi,
I experienced the issue mentioned in the title whenevever I tried to compile the library with SBCL 1.4.3.
I was told by the friendly folks on #sbcl to run SBCL with the --dynamic-space-size=8129 and it worked.

Since it took some hours of headscratching to find the solution, I wanded to post it here for others.

**Comment by j3pic** [comment]
@photz Is this a wontfix on their end? I don't have this problem with older versions of SBCL.

**Comment by photz** [comment]
@j3pic I remember that someone said they wanted to look into it, but otherwise no one seemed particularly alarmed by it.

**Comment by phoe** [comment]
I worked around this issue by splitting `binary.lisp` into two halves. This allowed me to load the system normally under SBCL 1.4.9 with standard heap sizes.

Modified `binary.lisp` and the `.asd` file: [lisp-binary.zip](https://github.com/heegaiximephoomeeghahyaiseekh/lisp-binary/files/2185561/lisp-binary.zip)

Log:

```
┌─[phoe][phoebox][±][master U:2 ?:1 ✗][~/Projects/Lisp/lisp-binary]
└─▪ ros run
* (ql:quickload :lisp-binary)
To load "lisp-binary":
  Load 1 ASDF system:
    lisp-binary
; Loading "lisp-binary"
..................................................
[package lisp-binary-utils].......................
[package lisp-binary/integer].....................
[package lisp-binary/float].......................
[package simple-bit-stream].......................
[package reverse-stream]..........................
[package lisp-binary].............................
......
(:LISP-BINARY)
* 
```

**Comment by j3pic** [comment]
Fixed thanks to @phoe
