### ISSUE TITLE
PUSHNEW instead of PUSH into *FEATURES*

### ISSUE THREAD

**Issue by phoe** [j3pic/lisp-binary#9]
Should be PUSHNEW on both L31 and L32.

https://github.com/heegaiximephoomeeghahyaiseekh/lisp-binary/blob/cdc49baa1d30f4813c16076fda290f18d33c77c7/float.lisp#L31

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
Fixed by https://github.com/heegaiximephoomeeghahyaiseekh/lisp-binary/pull/13
